# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cent <- function(A, X, y, l1, l2, tol, max_iter, verbose = 0L, scaled = 1L) {
    .Call(`_SuperCENT_cent`, A, X, y, l1, l2, tol, max_iter, verbose, scaled)
}

cv_oracle_cent <- function(A, X, y, lmin, lmax, gap, tol, max_iter, beta0, verbose = 0L, scaled = 1L, scaledn = 0L, d0_ = NULL, u0_ = NULL, v0_ = NULL, X_test_ = NULL, y_test_ = NULL, u_test0_ = NULL, v_test0_ = NULL) {
    .Call(`_SuperCENT_cv_oracle_cent`, A, X, y, lmin, lmax, gap, tol, max_iter, beta0, verbose, scaled, scaledn, d0_, u0_, v0_, X_test_, y_test_, u_test0_, v_test0_)
}

cv_cent <- function(A, X, y, lmin, lmax, gap, tol, max_iter, folds = 10L, verbose = 0L, scaled = 1L, scaledn = 0L, d0_ = NULL, u0_ = NULL, v0_ = NULL) {
    .Call(`_SuperCENT_cv_cent`, A, X, y, lmin, lmax, gap, tol, max_iter, folds, verbose, scaled, scaledn, d0_, u0_, v0_)
}

lr <- function(A, X, y, l, tol, max_iter, verbose = 0L, scaled = 1L) {
    .Call(`_SuperCENT_lr`, A, X, y, l, tol, max_iter, verbose, scaled)
}

cv_oracle_lr <- function(A, X, y, lmin, lmax, gap, tol, max_iter, beta0, verbose = 0L, scaled = 1L, scaledn = 0L, d0_ = NULL, u0_ = NULL, v0_ = NULL, X_test_ = NULL, y_test_ = NULL, u_test0_ = NULL, v_test0_ = NULL) {
    .Call(`_SuperCENT_cv_oracle_lr`, A, X, y, lmin, lmax, gap, tol, max_iter, beta0, verbose, scaled, scaledn, d0_, u0_, v0_, X_test_, y_test_, u_test0_, v_test0_)
}

cv_lr <- function(A, X, y, lmin, lmax, gap, tol, max_iter, folds = 10L, verbose = 0L, scaled = 1L, scaledn = 0L, d0_ = NULL, u0_ = NULL, v0_ = NULL) {
    .Call(`_SuperCENT_cv_lr`, A, X, y, lmin, lmax, gap, tol, max_iter, folds, verbose, scaled, scaledn, d0_, u0_, v0_)
}

cv_lr_2 <- function(A, X, y, lmin, lmax, gap, tol, max_iter, folds = 10L, verbose = 0L, scaled = 1L, scaledn = 0L, d0_ = NULL, u0_ = NULL, v0_ = NULL) {
    .Call(`_SuperCENT_cv_lr_2`, A, X, y, lmin, lmax, gap, tol, max_iter, folds, verbose, scaled, scaledn, d0_, u0_, v0_)
}

predict <- function(A, u_train, v_train, beta, X_test, tol, max_iter) {
    .Call(`_SuperCENT_predict`, A, u_train, v_train, beta, X_test, tol, max_iter)
}

predict_svd <- function(A, beta, X_test) {
    .Call(`_SuperCENT_predict_svd`, A, beta, X_test)
}

predict_oracle <- function(A, beta, X_test, u_test, v_test) {
    .Call(`_SuperCENT_predict_oracle`, A, beta, X_test, u_test, v_test)
}

lr_check <- function(A, X, y, u, v, beta, d, l, tol, max_iter, verbose, uv_is_init, u0) {
    .Call(`_SuperCENT_lr_check`, A, X, y, u, v, beta, d, l, tol, max_iter, verbose, uv_is_init, u0)
}

predict_uv_R <- function(A, u_train, v_train, u_test, v_test, tol = 1e-4, max_iter = 200L) {
    .Call(`_SuperCENT_predict_uv_R`, A, u_train, v_train, u_test, v_test, tol, max_iter)
}

two_stage_c <- function(A, X, y, tol, max_iter) {
    .Call(`_SuperCENT_two_stage_c`, A, X, y, tol, max_iter)
}

test_rirlba <- function(A) {
    .Call(`_SuperCENT_test_rirlba`, A)
}

